export * as Function from '@tsfun/function'
export * as Pipe from '@tsfun/pipe'
export * as Option from '@tsfun/option'
export * as Result from '@tsfun/result'
export * as Object from '@tsfun/object'
export * as Array from '@tsfun/array'
export * as Tap from '@tsfun/tap'
export * as Misc from '@tsfun/misc'
